API_HOST_URL: 'https://demo.grassroot.academy' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Grassroot Academy'
PLATFORM_NAME: 'Grassroot Academy'
PLATFORM_DESTINATION_NAME: 'https://demo.grassroot.academy'
FEEDBACK_EMAIL_ADDRESS: 'contact@demo.grassroot.academy'
